// frontend/src/components/DraggableList.svelte
<div class="draggable-list" bind:this={sortableList}>
  {#each $pointConfigs as point (point.id)}
    <div class="draggable-item">
      <div class="hamburger"></div>
      <div
        class="circle"
        style={`background-color: ${point.color.bg}; color: ${point.color.fg}`}
      >{point.id}</div>
      <div>({point.pos.x}, {point.pos.y})</div>
    </div>
  {/each}
</div>

<script lang="ts">
import { onMount, createEventDispatcher } from 'svelte';
import Sortable from "sortablejs";

import { points, pointConfigs } from "../stores/points";

const dispatch = createEventDispatcher<{changed: void}>();

let sortableList: HTMLDivElement

onMount(() => {
  Sortable.create(sortableList, {
    animation: 150,
    handle: ".hamburger",
    ghostClass: 'blue-background-class',
    onEnd: (evt) => {
      // Change order of items
      $points.splice(evt.newIndex, 0, ...$points.splice(evt.oldIndex, 1))
      dispatch("changed")
    }
  });
})

</script>

<style lang="scss">
.draggable-list {
  margin: 8px;
  padding: 16px;
  width: 300px;
  border: 1px solid rgba(0, 0, 0, 0.1);
  box-shadow: 8px 8px 8px rgba(0, 0, 0, 0.4);
}
.draggable-item {
  border: 2px solid rgba(0, 0, 0, 0.2);
  padding: 8px;
  margin: -2px 0px;
  display: flex;
  align-items: center;
}
.circle {
  width: 1.5em;
  height: 1.5em;
  border: 2px solid black;
  border-radius: 50%;
  margin-right: 0.5em;
  display: flex;
  justify-content: center;
  align-items: center;
}
.hamburger {
  width: 17px;
  height: 4px;
  color: rgba(0,0,0, 10%);
  background: currentColor;
  position: relative;
  margin-right: 8px;
  cursor: grab;
  &:before {
    content: "";
    position: absolute;
    top: -6px;
    width:  100%;
    height: 100%;
    background: currentColor;
  }
  &:after {
    content: "";
    position: absolute;
    top: 6px;
    width:  100%;
    height: 100%;
    background: currentColor;
  }
}
</style>

// frontend/src/components/DraggableList.vue
<template>
  <div class="draggable-wrapper">
    <draggable
      v-bind="options"
      :value="points"
      @input="(swappedList) => $emit('swap', swappedList)"
      @start="drag = true"
      @end="drag = false"
    >
      <transition-group type="transition" :name="!drag ? 'flip-list' : null">
        <div class="item-wrapper" v-for="point in points" :key="point.id">
          <span
            :style="{
              'background-color': point.color.bg,
              color: point.color.fg,
            }"
            class="item-color"
          >
            {{ point.id }}
          </span>
          {{ coordinate(point.pos) }}
        </div>
      </transition-group>
    </draggable>
  </div>
</template>

<script>
import draggable from "vuedraggable"
import { pointsValidator } from "@/utils/validator"

export default {
  name: "DraggableList",
  components: {
    draggable,
  },
  data() {
    return {
      drag: false,
      options: {
        animation: 200,
      },
    }
  },
  props: {
    points: {
      type: Array,
      required: true,
      validator: pointsValidator,
    },
  },
  methods: {
    coordinate(pos) {
      const { x, y } = pos
      return `(${parseInt(x, 10)}, ${parseInt(y, 10)})`
    },
  },
}
</script>

<style scoped>
.draggable-wrapper {
  overflow: scroll;
  width: 100%;
  height: 100%;
  border: 3px solid blue;
}
.item-wrapper {
  height: 2em;
  font-size: 1.4em;
  padding: 0.5ex 1ex;
  margin: 10px;
  font-weight: 400;
  font-family: monospace;
  text-align: center;
  border: 3px solid rgba(0, 0, 0, 0.3);
  box-shadow: 5px 5px 5px rgba(0, 0, 0, 0.2);

  display: flex;
  flex-direction: row;
  justify-content: flex-start;
  align-items: center;
}

.item-wrapper:hover {
  background-color: rgba(64, 128, 255, 0.3);
}

.item-color {
  display: flex;
  justify-content: center;
  align-items: center;
  width: 30px;
  height: 30px;
  margin-right: 8px;
  border-width: 3px;
  border-style: solid;
  border: 3px solid black;
  border-radius: 50%;
  color: black;
}
</style>
